simple:
  probability: 60
falseSimple:
  emeraldProbability: 120
monitored:
  fastProbability : 200
  red : 5
  green : 35
  blue : 60
  redContinuousRate: 6
  greenContinuousRate: 4
  blueContinuousRate: 3