simple:
  probability: 60
falseSimple:
  emeraldProbability: 120
monitored:
  fastProbability : 30
  red : 5
  green : 35
  blue : 60
  redContinuousRate : 50
  greenContinuousRate : 30
  blueContinuousRate : 10